{{ $svc := .Values.FrigateServiceUI }}
{{ $ports := list }}
{{ $ports = mustAppend $ports (dict "name" "mainfrigate" "port" $svc.port "nodePort" $svc.port "targetPort" "mainfrigate") }}
{{ $params := . }}
{{ $_ := set $params "commonService" (dict "ports" $ports ) }}
{{ if .Values.hostNetwork }}
{{ $_ := set $params.commonService "nameSuffix" "tcp-cluster-ip" }}
{{ $_1 := set $params.commonService "type" "ClusterIP" }}
{{ else }}
{{ $_ := set $params.commonService "nameSuffix" "tcp" }}
{{ $_1 := set $params.commonService "type" "NodePort" }}
{{ end }}
{{ include "common.classes.service" $params }}
