{{ $svc := .Values.homeassistant }}
{{ $ports := list }}
{{ $ports = mustAppend $ports (dict "name" "haserviceport" "port" $svc.port "nodePort" $svc.port "targetPort" "haserviceport") }}
{{ $params := . }}
{{ $_ := set $params "commonService" (dict "ports" $ports ) }}
{{ $_ := set $params.commonService "nameSuffix" "tcp-cluster-ip" }}
{{ $_1 := set $params.commonService "type" "ClusterIP" }}
{{ include "common.classes.service" $params }}
