name: mqtt
description: mqtt NVR
annotations:
  title: mqtt
type: application
version: 1.0.0
apiVersion: v2
appVersion: 2.0.15
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: tibhome
    url: https://www.tibhome.fr/
    email: trash@tibhome.fr
icon: https://www.motionsquare.fr/wp-content/uploads/2022/09/mqtt-logo-300x257.png
sources:
  - https://github.com/eclipse/mosquitto
keywords:
  - mqtt
