mqtt:
  image:
    pullPolicy: IfNotPresent
    repository: eclipse-mosquitto
    tag: 2.0.15
  port: 1883


securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0