mqtt:
  image:
    pullPolicy: IfNotPresent
    repository: eclipse-mosquitto
    tag: latest


securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0