homeassistant:
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/home-assistant/home-assistant
    tag: stable
  port: 8123


securityContext:
  privileged: true
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0