nginx:
  image:
    pullPolicy: IfNotPresent
    repository: nginx-tibhome
    tag: local
  port80: 80
  port443: 443


securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0