nginx:
  image:
    pullPolicy: IfNotPresent
    repository: tibhome/nginx-custom
    tag: local
  port80: 80
  port443: 443


securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0