name: frigate
description: Frigate NVR
annotations:
  title: frigate
type: application
version: 1.0.1
apiVersion: v2
appVersion: 0.12.1
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: tibhome
    url: https://www.tibhome.fr/
    email: trash@tibhome.fr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/frigate.png
sources:
  - https://github.com/blakeblackshear/frigate
keywords:
  - frigate
